basePath: /api/v1
definitions:
  main.ResponseError1:
    properties:
      errno:
        example: 11055
        type: integer
      extra:
        example: extra 1
        type: string
      message:
        example: error 1
        type: string
      payload:
        example: ""
        type: string
    type: object
  main.ResponseError2:
    properties:
      errno:
        example: 11068
        type: integer
      extra:
        example: extra 2
        type: string
      message:
        example: error 2
        type: string
      payload:
        example: ""
        type: string
    type: object
  main.ResponseError3:
    properties:
      errno:
        example: 11070
        type: integer
      extra:
        example: extra 3
        type: string
      message:
        example: error 3
        type: string
      payload:
        example: ""
        type: string
    type: object
  main.ResponseOk:
    properties:
      errno:
        example: 0
        type: integer
      extra:
        example: ""
        type: string
      message:
        example: ""
        type: string
      payload:
        example: '{"id": 4298009, "createDatetime": "2006-06-26T09:37Z08:00"}'
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /accounts:
    get:
      consumes:
      - application/json
      description: get accounts
      parameters:
      - description: name search by q
        format: email
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ResponseOk'
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.ResponseError1'
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/main.ResponseError2'
        "203":
          description: Non-Authoritative Information
          schema:
            $ref: '#/definitions/main.ResponseError3'
      summary: List accounts
      tags:
      - accounts
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ResponseOk'
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.ResponseError1'
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/main.ResponseError2'
        "203":
          description: Non-Authoritative Information
          schema:
            $ref: '#/definitions/main.ResponseError3'
      summary: Show an account
      tags:
      - accounts
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
